import './styles.css';
import './js/zoo.js';
import './js/ZooOperations.js';
import './js/AnimalModule.js'
import './js/AnimalAPI.js';
import './js/Security.js';
import './js/UiFeedback.js';
import './js/formsubmission.js';
import './js/zooLocations.js';
import './js/AnimalData.js';
import './js/AdminDashboard.js';
import './components/zoo-animal-card.js';
import './components/z-hover-highlight.js';
import './components/zoo-photo-booth.js';